name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MY_USER: melodiedivine@gmail.com
  MY_PASSWORD: 123456

jobs:
  greet:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    steps:
      - name: Say Hello
        run: echo "Hello! My name is ${USER_EMAIL}. My password is ${USER_PASSWORD}."

  lint:
    name: Lint (flake8)
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    continue-on-error: true     
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    steps:
      - uses: actions/checkout@v2
      - name: Install pytest
        run: pip install pytest
      - name: Run unit tests
        run: pytest tests/unit

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    needs: unit_tests
    if: github.ref == 'refs/heads/master'  
    environment:
      name: integration   
    steps:
      - uses: actions/checkout@v2
      - name: Install pytest
        run: pip install pytest
      - name: Run integration tests
        run: pytest tests/integration
